// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket_Hive.Data;

#nullable disable

namespace Ticket_Hive.Data.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20230415143728_imagefix")]
    partial class imagefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserModelEventModel", b =>
                {
                    b.Property<int>("EventsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("EventsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserModelEventModel");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.AppUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("NbrOfTickets")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventModelId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            DateTime = new DateTime(2023, 4, 25, 16, 37, 28, 620, DateTimeKind.Local).AddTicks(692),
                            EventType = "Nightclub",
                            Image = "/Images/EventImages/image 1",
                            Location = "Lund",
                            Name = "Kareoke bowling",
                            Price = 100m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 300,
                            DateTime = new DateTime(2023, 4, 20, 16, 37, 28, 620, DateTimeKind.Local).AddTicks(761),
                            EventType = "Musical",
                            Image = "/Images/EventImages/image 2",
                            Location = "Malmö",
                            Name = "Mama Mia",
                            Price = 200m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30000,
                            DateTime = new DateTime(2023, 5, 5, 16, 37, 28, 620, DateTimeKind.Local).AddTicks(765),
                            EventType = "Sport",
                            Image = "/Images/EventImages/image 3",
                            Location = "Stockholm",
                            Name = "AIK - Hammarby",
                            Price = 500m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            DateTime = new DateTime(2023, 4, 17, 16, 37, 28, 620, DateTimeKind.Local).AddTicks(768),
                            EventType = "Övrigt",
                            Image = "/Images/EventImages/image 4",
                            Location = "Halmstad",
                            Name = "Gästföreläsning med Steve Jobs",
                            Price = 10m,
                            TicketsSold = 20
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            DateTime = new DateTime(2023, 5, 10, 16, 37, 28, 620, DateTimeKind.Local).AddTicks(771),
                            EventType = "Sport",
                            Image = "/Images/EventImages/image 5",
                            Location = "Köpenhamn",
                            Name = "VM i Rally-Pingis",
                            Price = 25m,
                            TicketsSold = 0
                        });
                });

            modelBuilder.Entity("AppUserModelEventModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.BookingModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", null)
                        .WithMany("RecommendedEvents")
                        .HasForeignKey("EventModelId");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.AppUserModel", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.Navigation("RecommendedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
