// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket_Hive.Data;

#nullable disable

namespace Ticket_Hive.Data.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20230409210407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserModelEventModel", b =>
                {
                    b.Property<int>("EventsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("EventsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserModelEventModel");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.AppUserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("NbrOfTickets")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingCartModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ShoppingCartModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventModelId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.Property<int?>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            DateTime = new DateTime(2023, 4, 19, 23, 4, 7, 69, DateTimeKind.Local).AddTicks(9156),
                            EventType = "Nightclub",
                            Location = "Lund",
                            Name = "Kareoke bowling",
                            Price = 100m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 300,
                            DateTime = new DateTime(2023, 4, 14, 23, 4, 7, 69, DateTimeKind.Local).AddTicks(9205),
                            EventType = "Musical",
                            Location = "Malmö",
                            Name = "Mama Mia",
                            Price = 200m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30000,
                            DateTime = new DateTime(2023, 4, 29, 23, 4, 7, 69, DateTimeKind.Local).AddTicks(9208),
                            EventType = "Sport",
                            Location = "Stockholm",
                            Name = "AIK - Hammarby",
                            Price = 500m,
                            TicketsSold = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 20,
                            DateTime = new DateTime(2023, 4, 11, 23, 4, 7, 69, DateTimeKind.Local).AddTicks(9211),
                            EventType = "Övrigt",
                            Location = "Halmstad",
                            Name = "Gästföreläsning med Steve Jobs",
                            Price = 10m,
                            TicketsSold = 20
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            DateTime = new DateTime(2023, 5, 4, 23, 4, 7, 69, DateTimeKind.Local).AddTicks(9214),
                            EventType = "Sport",
                            Location = "Köpenhamn",
                            Name = "VM i Rally-Pingis",
                            Price = 25m,
                            TicketsSold = 0
                        });
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.ShoppingCartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.UserEvent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserModelId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("AppUserModelId");

                    b.HasIndex("EventId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("AppUserModelEventModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.BookingModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Hive.Data.Models.ShoppingCartModel", null)
                        .WithMany("Bookings")
                        .HasForeignKey("ShoppingCartModelId");

                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.EventModel", null)
                        .WithMany("RecommendedEvents")
                        .HasForeignKey("EventModelId");

                    b.HasOne("Ticket_Hive.Data.Models.UserModel", null)
                        .WithMany("Events")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.ShoppingCartModel", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.UserEvent", b =>
                {
                    b.HasOne("Ticket_Hive.Data.Models.AppUserModel", null)
                        .WithMany("UserEvents")
                        .HasForeignKey("AppUserModelId");

                    b.HasOne("Ticket_Hive.Data.Models.EventModel", "Event")
                        .WithMany("UserEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Hive.Data.Models.UserModel", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.AppUserModel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.EventModel", b =>
                {
                    b.Navigation("RecommendedEvents");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.ShoppingCartModel", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Ticket_Hive.Data.Models.UserModel", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
